blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/YOUR_ORG/YOUR_REPO/blob/main/README.md
    about: Check the documentation for guides and API references
  - name: Discussions
    url: https://github.com/YOUR_ORG/YOUR_REPO/discussions
    about: Ask questions and discuss ideas with the community
